# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: scss_compiler
version: '1.1'
author: Oliver Kreischer
supportpage: https://github.com/olien/scss_compiler/issues

page:
  title: 'SCSS Compiler'
  perm: scss_compiler[]
  icon: rex-icon fa-compress
  subpages:
      einstellungen: { title: 'translate:scss_compiler_setting',perm: scss_compiler[] }
      info:
        title: 'Info'
        subpages:
          info: { title: 'translate:info'}
          changelog: { title: 'translate:changelog'}
          license: { title: 'translate:license'}

