# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: scss_compiler
version: '0.1'
author: Oliver Kreischer
supportpage: http://www.redaxo.org/de/forum/

page:
  title: 'SCSS Compiler'
  perm: scss_compiler[]
  icon: rex-icon fa-compress
  subpages:
      einstellungen: { title: 'Einstellungen',perm: scss_compiler[] }
      info:
        title: 'Info'
        subpages:
          hilfe: { title: 'Hilfe'}
          changelog: { title: 'Changelog'}
          #lizenz: { title: 'Lizenz'}

