# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: scss_compiler
version: '1.6'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/scss_compiler

page:
  title: 'SCSS Compiler'
  perm: scss_compiler[]
  icon: rex-icon fa-compress
  subpages:
      einstellungen: { title: 'translate:scss_compiler_setting',perm: scss_compiler[] }
